build:
  stage: deploy
  script:
    - source $NANOCONFIGS/quantumpatch.config
    - ./tools/do_release_nanomatch.sh
  artifacts:
    paths:
      - simstackserver.zip
    expire_in: '26 weeks'
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  only:
    refs:
      - tags
