repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format
#  - repo: local
#    hooks:
#      - id: pixi-install
#        name: pixi-install
#        entry: pixi install -e mypy
#        language: system
#        always_run: true
#        require_serial: true
#        pass_filenames: false
#      - id: mypy
#        name: mypy
#        entry: "pixi run -e mypy mypy"
#        language: system
#        pass_filenames: false
#        require_serial: true
