package:
  name: simstackserver
  version: "1.5.4"
about:
  home: https://github.com/NanomatchGmbH/simstackserver
  license: proprietary
  summary:
source:
  git_url: ../
build:
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."
  noarch: python
requirements:
  build:
    - python >=3.10
    - python-build
    - setuptools
    - setuptools-scm
  run:
    - python >=3.10
    - appdirs >=1.4.4
    - Jinja2 >=3.0.3
    - lockfile >=0.12.2
    - lxml >=4.8.0
    - msgpack-python >=1.0.3
    - networkx >=2.7.1
    - numpy >=1.22.3
    - paramiko >=2.9.2
    - genson >=1.2.2
    - psutil >=5.9.0
    - python-daemon >=2.3.0
    - PyYAML >=6.0
    - pyzmq  >=22.3.0
    - sshtunnel >=0.4.0
    - jsonschema
    - nestdictmod >=1.1.0
    - pyparsing >=3.0.9
    - xmltodict >=0.12.0
    - clusterjob >=2.1.0,<2.2.0
    - threadfarm ==2.0.0
    - SQLAlchemy ==2.0.*
    - micromamba >=1.5.6
    - python-build
    - setuptools
test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
