name: "Build Conda Package"
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build_conda_package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: condabuild
      - name: Build
        id: build
        run: |
          pixi run condabuild --output-folder build/ --no-anaconda-upload
          OUTPUTFILE=$(pixi run condabuild --output --output-folder build/ --no-anaconda-upload)
          mkdir -p build/
          echo "releasepath=`realpath $OUTPUTFILE`" >> $GITHUB_OUTPUT

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: condapackage
          path: ${{ steps.build.outputs.releasepath }}

      - name: Upload to Repo
        id: upload
        run: |
          pixi auth login prefix.dev --token ${{ secrets.PREFIX_PUBLISH_KEY }}
          pixi upload https://prefix.dev/api/v1/upload/simstack ${{ steps.build.outputs.releasepath }}
